### ISSUE TITLE
Require Information

### ISSUE THREAD

**Issue by Noobman22** [Binondi/SplashZone#1]
please sir, share firebase database structure

**Comment by Binondi** [comment]
> please sir, share firebase database structure

See the project carefully then you can easily find out the structure of the project.
But i will give a breaf structure of the firebase below:
->category-> PUSH KEY(EX: fJerjJrh24jHh) -> category: "Anime",
categoryImageUrl: "your_image_url.jpg" .

-> Wallpapers -> PUSH KEY(EX: fJerjJrh24jHh) -> category : "Anime",
downloads : 0,
imageUrl : "your_wallpaper.jpg",
uid : PUSH KEY,
wpName : "Cool Anime Naruto Wallpaper
![Screenshot_20240410-175406](https://github.com/Binondi/SplashZone/assets/141143315/28445824-af21-49be-8a04-f12c68cc3d71)
"

**Comment by Noobman22** [comment]
thanxs a lot sir
